# Generated by Django 4.0.1 on 2022-01-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('street_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.PositiveIntegerField()),
                ('park_type', models.CharField(max_length=100)),
                ('trail_ratings', models.TextField()),
                ('accessibility', models.BooleanField()),
                ('description', models.TextField()),
                ('amenities', models.TextField()),
                ('trail_map', models.FileField(upload_to='maps/')),
                ('website', models.URLField()),
                ('challenge', models.BooleanField()),
                ('challenge_name', models.CharField(blank=True, max_length=100)),
                ('challenge_description', models.TextField(blank=True)),
            ],
        ),
    ]
