# Generated by Django 4.0.1 on 2022-01-31 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0003_park_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
