# Generated by Django 4.0.1 on 2022-02-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0007_alter_park_trail_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='phone',
            field=models.CharField(max_length=14),
        ),
    ]
