# Generated by Django 4.0.1 on 2022-02-07 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0008_alter_park_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='park_type',
            field=models.CharField(default='Indiana State Park', max_length=100),
        ),
        migrations.AlterField(
            model_name='park',
            name='state',
            field=models.CharField(default='IN', max_length=100),
        ),
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('distance', models.CharField(blank=True, max_length=7)),
                ('rating', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('accessible', models.BooleanField(default=False)),
                ('park_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parks.park')),
            ],
        ),
    ]
