# Generated by Django 4.0.1 on 2022-02-13 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0009_alter_park_park_type_alter_park_state_trail'),
        ('hikers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('distance', models.DecimalField(blank=True, decimal_places=1, max_digits=4)),
                ('notes', models.TextField(blank=True)),
                ('hiker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hikers.hiker')),
                ('park_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parks.park')),
                ('trails', models.ManyToManyField(to='parks.Trail')),
            ],
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.UniqueConstraint(fields=('hiker_id', 'park_id', 'date'), name='unique_trip'),
        ),
    ]
