# Generated by Django 4.0.1 on 2022-02-13 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hikers', '0003_rename_visit_hike_remove_hike_unique_trip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hike',
            name='test',
            field=models.DateField(blank=True, null=True),
        ),
    ]
