# Generated by Django 4.0.1 on 2022-02-13 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hikers', '0004_hike_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hike',
            name='test',
        ),
    ]
