# Generated by Django 4.0.1 on 2022-02-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hikers', '0005_remove_hike_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiker',
            name='registered',
            field=models.DateField(auto_now_add=True),
        ),
    ]
