# Generated by Django 4.0.1 on 2022-02-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hikers', '0006_alter_hiker_registered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiker',
            name='password',
        ),
        migrations.RemoveField(
            model_name='hiker',
            name='username',
        ),
        migrations.AlterField(
            model_name='hiker',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
